FROM circleci/node:10.14.2@sha256:3e3d26995b62394bb7560beb417a01bea1a8abf6391cdd80b6d3149b44d886f1
LABEL maintainer="https://teamdigitale.governo.it"

RUN sudo apt-get -y install --no-install-recommends libunwind8=1.1-4.1
